apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-10-04T12:55:10Z"
  generation: 1
  labels:
    app: carrental
  name: carrental
  namespace: default
  resourceVersion: "6022"
  uid: f3edf75b-59b6-4116-9cd0-52ddbc3b18a6
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: carrental
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: carrental
    spec:
      containers:
      - image: carrental:1.0
        imagePullPolicy: IfNotPresent
        name: carrental
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-10-04T12:55:14Z"
    lastUpdateTime: "2025-10-04T12:55:14Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-04T12:55:10Z"
    lastUpdateTime: "2025-10-04T12:55:14Z"
    message: ReplicaSet "carrental-754d85f666" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
