apiVersion: apps/v1
kind: Deployment
metadata:
  name: pneumonia-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pneumonia-app
  template:
    metadata:
      labels:
        app: pneumonia-app
    spec:
      containers:
        - name: pneumonia-app
          image: pneumonia-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: pneumonia-app-service
spec:
  type: LoadBalancer
  selector:
    app: pneumonia-app
  ports:
    - port: 5000
      targetPort: 5000

